# Setting server port HTTP
server:
  port: 8090

# Setting parameters for connection PostegresSQL & JPA + Hibernate
spring:
  application:
    name: mclyne
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/mclyne
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

